xen-troops/displ_be

src/displayBackend/wayland/SeatDevice.hpp
src/displayBackend/wayland/SeatTouch.cpp
src/displayBackend/wayland/SeatTouch.hpp

Each seat device uses mCurrentCallback field to keep
frontend handler when input device entered the surface.
It is ok for keyboard and mouse but in case multitouch
user can press different surface with different touch ID
and using one current callback is not enough. The fix is
to have current callback per touch ID.

SeatTouch: fix callbacks handling

---

src/displayBackend/drm/FrameBuffer.cpp

Fix local variable initialization in FrameBuffer::init

---

src/displayBackend/wayland/CMakeLists.txt
src/displayBackend/wayland/Connector.cpp
src/displayBackend/wayland/Connector.hpp
src/displayBackend/wayland/Display.cpp
src/displayBackend/wayland/SeatDevice.hpp
src/displayBackend/wayland/SeatKeyboard.cpp
src/displayBackend/wayland/SeatPointer.cpp
src/displayBackend/wayland/SeatTouch.cpp
src/displayBackend/wayland/SurfaceManager.cpp
src/displayBackend/wayland/SurfaceManager.hpp

Currently wl surface is created once per connector. On init/release shell surface is created/destroyed
and it is not possible to reuse wl surface. The fix is pass wl compositor to connector and create/delete
surface together with shell surface.

Wayland: create wl surface on init connector and destroy on release

---

src/displayBackend/drm/Dumb.cpp
src/displayBackend/drm/Dumb.hpp

Block until dumb buffer with the wait handle provided be freed:
this is needed for synchronization between frontend and backend in case
frontend provides grant references of the buffer via
DRM_XEN_ZCOPY_DUMB_FROM_REFS IOCTL and which must be released before
backend replies with XENDISPL_OP_DBUF_DESTROY response.
Signed-off-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>

Wait for the zero-copy buffer to be freed

---

src/displayBackend/drm/Dumb.cpp
src/displayBackend/wayland/Display.cpp

There is a portability note on errno usage:
https://www.gnu.org/software/libc/manual/html_node/Checking-for-Errors.html
"Portability Note: ISO C specifies errno as a "modifiable lvalue" rather
than as a variable, permitting it to be implemented as a macro."
Use brackets around errno check for code portability.
Signed-off-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>

Make errno check portable

---

src/displayBackend/wayland/Display.cpp

In wayland dispatch thread other than wayland errors
may occur. The fix checks if there was wayland error
then handle wayland error otherwise print exception
message.

Fix wayland error handling

---

src/displayBackend/wayland/Connector.cpp

Calling release connector if it is released is valid case.
This patch add checking to allow release on released connector.

Wayland: do not delete surface if it is deleted on release connector

---

src/displayBackend/wayland/FrameBuffer.cpp
src/displayBackend/wayland/FrameBuffer.hpp
src/displayBackend/wayland/SharedMemory.cpp
src/displayBackend/wayland/SharedMemory.hpp
src/displayBackend/wayland/WaylandZCopy.cpp
src/displayBackend/wayland/WaylandZCopy.hpp

Wayland switches own fd to hang up state and generates
error too late in case of creating surface with
unsupported pixel format. This patch stores supported
pixel formats into a list and check this list
before creating a surface. In case format is unsupported
proper exception is generated.

Wayland: add handling of unsupported pixel format

---

src/main.cpp

Due to default seg fault handler is overriden to generate
stack trace, core dump is not generated. The fix is to restore
default handler and send SIGSEGV to itself.

Fix generating core dump on segmentation fault

---

src/displayBackend/DisplayCommandHandler.cpp
src/displayBackend/wayland/FrameBuffer.cpp
src/displayBackend/wayland/FrameBuffer.hpp
src/displayBackend/wayland/Surface.cpp
src/displayBackend/wayland/Surface.hpp

This PR includes following fixes:
* push null buffer to weston when current buffer is deleted;
* if connector is initialized second time, perform reinitialize.

Fixes to follow new DRM behavior

---

src/displayBackend/wayland/Surface.cpp

Currently surface is cleared in wrong place. As result wl_buffer
keeps pointer to the surface even after surface is deleted. It leads
to crash if the frame buffer is destroyed after connector (surface)
release.

Wayland: clear surface for wl buffer on surface destroy

---

src/displayBackend/DisplayItf.hpp

Add include <functional> explicitly to DisplayItf.hpp

Fix gcc7 compilation error

---

src/displayBackend/DisplayBackend.cpp

In new display protocol new field "unique_id" was introduced to distinguish
connectors. This patch add using proper define XENDISPL_FIELD_UNIQUE_ID to
address this field.

DisplayBackend: use XENDISPL_FIELD_UNIQUE_ID define instead of "id"

---

src/inputBackend/InputBackend.cpp

In new kbd protocol new field "unique_id" was introduced. This patch add
using define XENKBD_FIELD_UNIQUE_ID to address this field.

InputBackend: use XENKBD_FIELD_UNIQUE_ID define instead of "id"

---

src/displayBackend/DisplayBackend.cpp
src/displayBackend/DisplayBackend.hpp
src/inputBackend/InputBackend.cpp
src/inputBackend/InputBackend.hpp
src/main.cpp

We've submitted renaming VKBD to VINPUT to Xen. Once these changes are acceptable, we should rename it on our backend side. This commit should be merged once https://github.com/xen-troops/libxenbe/pull/47 is merged.

Rename VKBD backend device name from VKBD to VINPUT

---

src/displayBackend/DisplayCommandHandler.cpp

Fixes: 6bcf9acb219e ("Handle buffer offset passed with XENDISPL_OP_DBUF_CREATE v2")
Signed-off-by: Oleksandr Andrushchenko <oleksandr_andrushchenko@epam.com>

Fix compile error for XENDISPL_OP_DBUF_CREATE before v2

---

src/displayBackend/drm/Dumb.cpp
src/displayBackend/drm/Dumb.hpp

Fix of crash when strides are different
There are situations when a backend DRM driver makes a buffer bigger size than a frontend buffer.
For example, i915 driver counts a stride by a multiplication of a display width in pixesl on a number of bytes per pixel
and aligns it up to 64 bytes. Then a size of the buffer is counted by a multiplication of the stride on a display height.
So we have the backend buffer is bigger than the frontend buffer with an unaligned stride.
It causes a crash when bytes are coping from the frontend buffer to the backend buffer with the size of the backend buffer.
In a case when we do not use zero-copying the situation can be fixed by coping of lines of the frontend buffer to beginning of lines of the backend buffer one by one.
This fix is only suitable in the …

Fix of crash v2

---

src/displayBackend/common/ConnectorBase.cpp
src/displayBackend/common/ConnectorBase.hpp
src/displayBackend/common/drm_edid.h

Use Display Product Name (ASCII) String Descriptor to
store display name. This may be critical for some OS like Android.
Signed-off-by: Andrii Chepurnyi <andrii_chepurnyi@epam.com>

DisplayBackend: Add display name to the EDID

---

src/displayBackend/drm/Display.hpp

Specifier 'explicit' is used to avoid the unexpected type deduction.
The constructor of class Display has 2 input parameters of different type.
So, it is not necessary to the explicit specifier here, because it is not possible
to be int and bool types simultaneously.
Summary: specifier explicit does not bring any advantages and may be removed.
Signed-off-by: Ihor Usyk <ihor_usyk@epam.com>

Remove explicit specifier from constructor of class Display

---

src/main.cpp

Remove ':' because option -f has no argument.
Add short description of -f to help message.
Signed-off-by: Ruslan Shymkevych <ruslan_shymkevych@epam.com>

Minor fixes regarding -f option

---

src/displayBackend/DisplayCommandHandler.cpp

Add the set of the 'assert's to simplify the initialization errors
during the object creation.
Signed-off-by: Ihor Usyk <ihor_usyk@epam.com>

DisplayCommandHandler: add the verification of nullptr

---

src/displayBackend/common/CMakeLists.txt
src/displayBackend/common/ConnectorBase.cpp
src/displayBackend/common/ConnectorBase.hpp
src/displayBackend/common/DisplayItf.hpp
src/displayBackend/common/Edid.cpp
src/displayBackend/common/Edid.hpp

Add 'const' and 'static' to some methods.
The methods are not using the class members or methods
must be declared as static, there are
ConnectorBase::edidPutDetailedTimin
ConnectorBase::edidPutTimings
ConnectorBase::edidPutColorSpace
ConnectorBase::edidPutEssentials
ConnectorBase::edidPutBlockCheckSum
The memebrs that are const must be static
There are
ConnectorBase::EDID_MANUFACTURING_YEAR
ConnectorBase::EDID_DPI
ConnectorBase::EDID_REFRESH_RATE_HZ
The methods to return the value and not modify
the object state, must be 'const'.
There are
Connector::getEDID
The ConnectorBase::edidPutTimings has been modified to
support 'const' for Connector::getEDID.
Signed-off-by: Ihor Usyk <ihor_usyk@epam.com>
Reviewed-by: Volodymyr Babchuk <volodymyr_babchuk@epam.com>

Private methods should be static
