- src/Config.cpp
> Fix error when there is no section in config file

- CMakeLists.txt
- Version.hpp.in
- generateVersion.cmake
- src/main.cpp
> Add versioning

- CMakeLists.txt
- generateVersion.cmake
> Fix getting version if cmake is done out of source folder

- src/displayBackend/wayland/SharedFile.cpp
> WL: fix creating shared file if w,h == 0

- src/displayBackend/wayland/SharedFile.cpp
Reverts xen-troops/displ_be#34
> Revert "WL: fix creating shared file if w,h == 0"

- src/displayBackend/BuffersStorage.cpp
- src/displayBackend/DisplayCommandHandler.cpp
- src/displayBackend/DisplayItf.hpp
- src/displayBackend/drm/Connector.cpp
- src/displayBackend/drm/Display.cpp
- src/displayBackend/drm/Dumb.cpp
- src/displayBackend/drm/DumbZCopyBack.cpp
- src/displayBackend/drm/DumbZCopyFront.cpp
- src/displayBackend/drm/FrameBuffer.cpp
- src/displayBackend/drm/Modes.cpp
- src/displayBackend/wayland/Compositor.cpp
- src/displayBackend/wayland/Display.cpp
- src/displayBackend/wayland/DrmBuffer.cpp
- src/displayBackend/wayland/IviApplication.cpp
- src/displayBackend/wayland/IviSurface.cpp
- src/displayBackend/wayland/Seat.cpp
- src/displayBackend/wayland/SeatKeyboard.cpp
- src/displayBackend/wayland/SeatPointer.cpp
- src/displayBackend/wayland/SeatTouch.cpp
- src/displayBackend/wayland/SharedBuffer.cpp
- src/displayBackend/wayland/SharedFile.cpp
- src/displayBackend/wayland/SharedMemory.cpp
- src/displayBackend/wayland/Shell.cpp
- src/displayBackend/wayland/ShellSurface.cpp
- src/displayBackend/wayland/Surface.cpp
- src/displayBackend/wayland/WaylandDrm.cpp
- src/inputBackend/InputBackend.cpp
- src/inputBackend/InputItf.hpp
- src/inputBackend/input/DevInput.cpp
- src/main.cpp
> Add error code to exceptions

- src/CMakeLists.txt
- src/displayBackend/wayland/CMakeLists.txt
> cmake: set ivi libraries if pkg not found

- src/main.cpp
> Fix creating input backend if it is disabled in config

- src/displayBackend/wayland/Display.cpp
> weyland: fix high CPU consumption

- src/displayBackend/DisplayItf.hpp
- src/displayBackend/drm/Dumb.hpp
- src/displayBackend/drm/DumbZCopyBack.hpp
- src/displayBackend/drm/DumbZCopyFront.hpp
- src/displayBackend/wayland/CMakeLists.txt
- src/displayBackend/wayland/Display.cpp
- src/displayBackend/wayland/Display.hpp
- src/displayBackend/wayland/KmsBuffer.cpp
- src/displayBackend/wayland/KmsBuffer.hpp
- src/displayBackend/wayland/SharedBuffer.cpp
- src/displayBackend/wayland/SharedFile.hpp
- src/displayBackend/wayland/WaylandKms.cpp
- src/displayBackend/wayland/WaylandKms.hpp
- src/displayBackend/wayland/protocols/CMakeLists.txt
- src/displayBackend/wayland/protocols/wayland-kms.xml
> Add wayland-kms

- src/displayBackend/wayland/DrmBuffer.cpp
- src/displayBackend/wayland/KmsBuffer.cpp
Signed-off-by: al1 <al1img@gmail.com>
> Fix log names in kms and drm buffers

- src/displayBackend/drm/DumbZCopyBack.hpp
- src/displayBackend/drm/DumbZCopyFront.hpp
Signed-off-by: al1 <al1img@gmail.com>
> ZCopy: fix returning dumb handles

- src/displayBackend/BuffersStorage.cpp
- src/displayBackend/BuffersStorage.hpp
- src/displayBackend/DisplayCommandHandler.cpp
Signed-off-by: Oleksandr Grytsov <al1img@gmail.com>
> Add flush command on closing frontend

- src/displayBackend/drm/Dumb.cpp
> Fix errno using on DumbZCopyFront destroy

- src/displayBackend/drm/Dumb.cpp
- src/displayBackend/wayland/CMakeLists.txt
- src/displayBackend/wayland/Display.hpp
> Fix WITH_ZCOPY=OFF compilation

- src/main.cpp
> Fix return main failure status when error occurse

- src/displayBackend/wayland/Display.cpp
- src/displayBackend/wayland/Display.hpp
Set wayland log hander to print wayland client errors
> Set wayland log handler

- src/displayBackend/wayland/Connector.cpp
- src/displayBackend/wayland/Connector.hpp
> Wayland: do not create surfaces if connector initialized

- src/displayBackend/wayland/SeatTouch.cpp
- src/displayBackend/wayland/SeatTouch.hpp
- src/inputBackend/InputBackend.cpp
- src/inputBackend/InputBackend.hpp
- src/inputBackend/InputItf.hpp
- src/inputBackend/input/DevInput.cpp
- src/test.cpp
> touch: fix event sending sequence

- src/displayBackend/wayland/IviApplication.cpp
> IviApplication remove old ilmClient include

- src/displayBackend/wayland/Surface.cpp
- src/displayBackend/wayland/Surface.hpp
If surface is hidden or overlapped by other
surfaces, weston will not send frame done callback.
This fix introduces timeout 50 msec to wait
frame callback. If there is no callback during this
timeout backend will send flip event to the frontend.
Also backend will send immediate frame event on all
further flip requests till weston frame callback
received.
> Wl Surface: add frame handler timeout

- src/displayBackend/BuffersStorage.cpp
- src/displayBackend/BuffersStorage.hpp
- src/displayBackend/DisplayCommandHandler.cpp
- src/displayBackend/wayland/Connector.cpp
- src/displayBackend/wayland/Connector.hpp
- src/displayBackend/wayland/Surface.cpp
This PR fixes remaining grefs after DomA reboot
> Fix surfaces release sequence

- CMakeLists.txt
> Use git command if git package not found for version generating

- src/displayBackend/wayland/Connector.cpp
> Wayland: check if connector is initialized before page flip

- src/displayBackend/DisplayCommandHandler.cpp
- src/displayBackend/DisplayItf.hpp
- src/displayBackend/drm/Connector.cpp
- src/displayBackend/drm/Connector.hpp
- src/displayBackend/wayland/Connector.cpp
- src/displayBackend/wayland/Connector.hpp
This reverts commit 372aaff22298481646b20fe7bfca0a1782c466be.
> Revert "Display: send flip event on set config"

- README.md
Signed-off-by: Pau Pajuelo <ppajuel@gmail.com>
> README.md: Replace id to unique-id into input configuration examples

- src/main.cpp
Fix of a build when WITH_DRM=OFF or WITH_WAYLAND=OFF specified
> Fix of build without DRM or WAYLAND
